- lib/main.dart
- lib/models.dart
- test/widget_test.dart
At least now it says "CruiseMonkey" somewhere.
> Replace the template with a blank app.

- lib/main.dart
- lib/src/json.dart
- lib/src/logic/cruise.dart
- lib/src/models/user.dart
- lib/src/network/rest.dart
- lib/src/network/twitarr.dart
- lib/src/views/create_account.dart
- lib/src/views/drawer.dart
- lib/src/views/profile.dart
- lib/src/views/seamail.dart
- lib/src/views/settings.dart
- test/loggers.dart
- test/mocks.dart
- test/nulls.dart
...and some updates to handle recent API changes on the server
> Update profile on focus loss

- lib/src/logic/cruise.dart
- lib/src/logic/forums.dart
- lib/src/logic/photo_manager.dart
- lib/src/logic/store.dart
- lib/src/logic/stream.dart
- lib/src/network/rest.dart
- lib/src/network/twitarr.dart
- lib/src/views/forums.dart
- lib/src/views/seamail.dart
- lib/src/views/stream.dart
- lib/src/widgets.dart
- test/loggers.dart
- test/mocks.dart
- test/nulls.dart
- test/views/profile_test.dart
...and all but the UI for actually sending them too.
> View images in forums and tweets

- lib/src/logic/cruise.dart
- lib/src/models/user.dart
- lib/src/network/rest.dart
- lib/src/network/twitarr.dart
- lib/src/views/attach_image.dart
- lib/src/views/create_account.dart
- lib/src/views/forums.dart
- lib/src/views/profile.dart
- lib/src/views/seamail.dart
- lib/src/views/stream.dart
- lib/src/widgets.dart
- test/loggers.dart
- test/logic/user_test.dart
- test/mocks.dart
- test/nulls.dart
- test/views/profile_test.dart
Specifically: pronouns, image upload in twitarr and forums and forum creation, fixed some bugs, made the image display prettier, made clicking an image show it full screen, and improved some of the help text.
￼
> Image upload

- lib/main.dart
- lib/src/logic/cruise.dart
- lib/src/network/rest.dart
- lib/src/network/twitarr.dart
- lib/src/progress.dart
- lib/src/views/settings.dart
- test/loggers.dart
- test/logic/cruise_model_test.dart
- test/mocks.dart
- test/nulls.dart
- test/views/profile_test.dart
- test/views/settings_test.dart
Should make things a little more reliable.
> Rejigger some low-level login logic

- ios/.gitignore
- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- ios/Runner.xcworkspace/contents.xcworkspacedata
- ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- ios/Runner/Info.plist
Here's everything that was updated as I got the project building and deployed to the iOS app store.
> add/update build artifacts for iOS deployment

- android/app/src/main/AndroidManifest.xml
#100 Fixes the SecurityException, tested on the 6.0 emulator.
> Add WAKE_LOCK permission

- lib/src/network/rest.dart
- lib/src/views/forums.dart
- lib/src/views/seamail.dart
- lib/src/views/stream.dart
Fixes https://github.com/seamonkeysocial/cruisemonkey/issues/178
> Don't allow ' ' as input.

- lib/src/network/rest.dart
- lib/src/widgets.dart
Fixes https://github.com/seamonkeysocial/cruisemonkey/issues/162
> Stop weird bounce on create account page.

- lib/main.dart
> Change app title for app switcher

- lib/main.dart
- lib/src/logic/background_polling.dart
- lib/src/logic/store.dart
- lib/src/views/settings.dart
- test/views/settings_test.dart
Fixes https://github.com/seamonkeysocial/cruisemonkey/issues/184
> Allow mail checking interval to be configured

- lib/main.dart
- lib/src/logic/cruise.dart
- lib/src/logic/forums.dart
- lib/src/logic/mentions.dart
- lib/src/logic/seamail.dart
- lib/src/network/rest.dart
- lib/src/network/twitarr.dart
- lib/src/views/comms.dart
- lib/src/views/mentions.dart
- test/loggers.dart
- test/mocks.dart
> Mentions page

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
These are just changes to various build stuff when making iOS releases.
> Updates from doing iOS builds

- lib/src/widgets.dart
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/213
> Improve spacing in code of conduct text.

- lib/src/logic/forums.dart
- lib/src/logic/mentions.dart
- lib/src/logic/seamail.dart
- lib/src/models/user.dart
- lib/src/utils.dart
- lib/src/views/calendar.dart
- lib/src/views/comms.dart
- lib/src/views/deck_plans.dart
- lib/src/views/seamail.dart
- lib/src/views/user.dart
- lib/src/widgets.dart
- test/views/deck_plans_test.dart
- test/views/forums_test.dart
- test/views/user_test.dart
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/260 (default subject line in seamail)
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/261 (jump to top in forum and seamail lists)
Default deck is now 9 Lido.
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/262 (suggest airplane mode plus WiFi if cannot connect)
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/259 (moved the "4 days ago" text to another line to make room)
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/257 (use 24h time)
> Minor improvements througout.

- lib/main.dart
- lib/src/logic/cruise.dart
- lib/src/logic/forums.dart
- lib/src/models/errors.dart
- lib/src/network/rest.dart
- lib/src/pretty_text.dart
- lib/src/searchable_list.dart
- lib/src/views/games.dart
- lib/src/views/karaoke.dart
- lib/src/views/search.dart
- lib/src/views/user.dart
- lib/src/widgets.dart
- pubspec.yaml
- test/views/karaoke_test.dart
- test/views/user_test.dart
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/251 (tappable usernames)
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/153 (tappable hashtags)
Also makes links tappable.
> Pretty print text more

- lib/src/network/rest.dart
- lib/src/views/profile.dart
- lib/src/views/profile_editor.dart
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/272
> Clarify profile UI

- lib/src/progress.dart
- lib/src/searchable_list.dart
- lib/src/views/comms.dart
- lib/src/views/games.dart
- lib/src/views/karaoke.dart
- lib/src/views/search.dart
- test/views/karaoke_test.dart
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/280
> Search/sort in Karaoke

- lib/src/pretty_text.dart
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/288
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/286
> Minor tweaks to the rendering and linkifying

- lib/src/views/seamail.dart
Bug was caused by https://github.com/flutter/flutter/pull/42936 as reported by https://github.com/flutter/flutter/issues/44550.
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/291
> Workaround for Flutter change to AppBar behaviour

- MANUAL_TESTING.md
- android/app/src/main/AndroidManifest.xml
- lib/src/logic/cruise.dart
- lib/src/widgets.dart
- pubspec.yaml
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/106
> Save image to album

- lib/main.dart
- lib/src/views/seamail.dart
- lib/src/widgets.dart
Fixes https://github.com/seamonkeysocial/rainbowmonkey/issues/311
> Don't show a message as unread when you're reading it

- lib/main.dart
- lib/src/logic/background_polling.dart
- lib/src/logic/cruise.dart
- lib/src/models/server_status.dart
- lib/src/network/rest.dart
- lib/src/network/settings.dart
- lib/src/network/twitarr.dart
- lib/src/views/forums.dart
- lib/src/views/seamail.dart
- lib/src/views/settings.dart
- lib/src/views/stream.dart
- lib/src/widgets.dart
- test/loggers.dart
- test/logic/cruise_model_test.dart
- test/views/forums_test.dart
- test/views/profile_test.dart
- test/views/settings_test.dart
I'm sure I broke something critical here.
* make search disablable
* use rainbow_monkey keys for section control
* let server control poll frequency
* fix alignment of text fields
* fix image sizing of small images
* use modern snackbar style
* update the server presets
* use encryption by default on the ship
* add some random backoff when contacting server
> Lots of last-minute fixes

- lib/src/logic/forums.dart
- lib/src/views/forums.dart
> Force thread to be read when rendered.

- lib/main.dart
- lib/src/views/attach_image.dart
- lib/src/views/calendar.dart
- lib/src/views/clock.dart
- lib/src/views/create_account.dart
- lib/src/views/login.dart
- lib/src/views/profile_editor.dart
- lib/src/views/settings.dart
- lib/src/views/user.dart
- lib/src/widgets.dart
Replaced obsolete references to RaisedButton with ElevatedButton and FlatButton with TextButton per flutter/flutter#59702.
> Replaced FlatButton with TextButton, RaisedButton with ElevatedButton

- lib/src/views/attach_image.dart
In https://github.com/jocosocial/rainbowmonkey/pull/336 I missed one reference to accentTextTheme. Updated it here.
> Updated one more accentTextTheme reference

- lib/main.dart
Removed the workaround for #49984 in makeTheme() because the issue has been resolved: #74610
> Removed obsolete workaround for #49984
